### PR TITLE
Anony

### PR DESCRIPTION
**Pull request by Yiyun-Liang**
@tangdian

### CODE REVIEW

**Comment by tangdian** [comment]
Why it looks so strange... it seems like you didn't pull my changes to GET one posting, but how can this happen in Git? I am confused...

**Comment by tangdian** [comment]
Oh I see, the thing is:  you didn't pull my updates, and you updated and tried to commit, and you see the conflicts and you add and commit again...

**Comment by tangdian** [comment]
Why would you like to use find instead of findOne in GET posting/:id ? Is there any magical implication here?

**Comment by Yiyun-Liang** [comment]
don't know what happened..... should be copied from your previous code...

**Comment by tangdian** [comment]
Alright, thanks for your work! For next time, please remember to pull first in case I made any change to your branch. Also, please try to merge and fix any conflict with master before any Pull Request. :)

**Comment by Yiyun-Liang** [comment]
my bad

**Comment by Yiyun-Liang** [comment]
ok now

**Comment by tangdian** [comment]
# Nice Job!

**Comment by Yiyun-Liang** [comment]
:(

**Comment by tangdian** [comment]
Why being sad...

## Remember
# Be Happy

It's fun to play with markdown in comments hahaha

**Comment by Yiyun-Liang** [comment]
i am going to get dark green contribution today...

**Comment by tangdian** [comment]
Fun fact: if you keep your contribution number to 4 everyday, then every day will be a dark green. But if you make 100 contributions one day and 50 contributions every other day, you can only get one dark green.

**Comment by Yiyun-Liang** [comment]
oh good to know that, i was planning to draw a heart on that chart

**Comment by Yiyun-Liang** [comment]
are u going to merge it?

**Comment by tangdian** [comment]
Yes, of course, but I will do it after I get home, like 8 p.m. PST, since I still need to do some minor modifications

**Comment by TeakayAero** [comment]
why is no chinese comment going on here

**Comment by tangdian** [comment]
# Open source is beyond language, you know. 

Actually, it's because I failed to install Chinese Shurufa on my working laptop for some inapparent reasons =_=

**Pull request merged**
